Resources:
  # DynamoDB Tables
  
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.users}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: user_sub
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserSubIndex
          KeySchema:
            - AttributeName: user_sub
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  UserRateLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.userRateLimitsV2}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: minute_timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: minute_timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
      # Note: user_id is used as partition key for consistency across all tables
      # We already have user_id after the user account lookup (required for quota checks, billing, etc.)
  
  JobDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.jobDetails}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdCreatedAtIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  AnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.analytics}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  PlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.plans}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: plan_id
          AttributeType: S
      KeySchema:
        - AttributeName: plan_id
          KeyType: HASH
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  ApiKeysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.apiKeys}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: api_key
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: api_key_id
          AttributeType: S
      KeySchema:
        - AttributeName: api_key
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: ApiKeyIdIndex
          KeySchema:
            - AttributeName: api_key_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  BillsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.bills}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: billing_month
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: billing_month
          KeyType: RANGE
      # GSI removed - primary key (user_id + billing_month) can be queried directly
      # No need for redundant GSI with same structure
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  WebhooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.webhooks}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: webhook_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: is_active
          AttributeType: S
      KeySchema:
        - AttributeName: webhook_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserIdStatusIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: is_active
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  WebhookHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.${self:provider.stage}.webhookHistory}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: webhook_id
          AttributeType: S
        - AttributeName: delivery_id
          AttributeType: S
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: delivered_at
          AttributeType: S
      KeySchema:
        - AttributeName: webhook_id
          KeyType: HASH
        - AttributeName: delivery_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: JobIdIndex
          KeySchema:
            - AttributeName: job_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserIdTimestampIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: delivered_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      # Note: TTL is disabled - webhook history is kept permanently for debugging, auditing, and troubleshooting
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  # S3 Bucket for PDF Storage
  
  PDFsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: podpdf-${self:provider.stage}-pdfs
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldPDFs
            Status: Enabled
            ExpirationInDays: 1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  # SQS Queue for Long Job Processing
  
  LongJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: podpdf-${self:provider.stage}-longjob-queue
      VisibilityTimeout: 900
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 0
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: podpdf
  
  # Cognito User Pool
  
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: podpdf-${self:provider.stage}-user-pool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailSubject: "Verify your PodPDF account"
        # Cognito requires the placeholder {####}; with CONFIRM_WITH_CODE it becomes a verification code
        EmailMessage: "Your verification code is: {####}"
      LambdaConfig:
        PostConfirmation: !Sub 
          - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionName}'
          - FunctionName: podpdf-${self:provider.stage}-cognito-post-confirmation
      UserPoolTags:
        Stage: ${self:provider.stage}
        Service: podpdf
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: podpdf-${self:provider.stage}-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:3000/auth/callback
        - https://yourdomain.com/auth/callback
      LogoutURLs:
        - http://localhost:3000/auth/logout
        - https://yourdomain.com/auth/logout
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30
  
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: podpdf-${self:provider.stage}-auth
      UserPoolId: !Ref CognitoUserPool
  
  # Note: Lambda Permission for Post Confirmation trigger is automatically created by Serverless Framework
  # when using cognitoUserPool events in serverless.yml. No manual permission needed.

Outputs:
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: ${self:provider.stage}-CognitoUserPoolId
  
  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: ${self:provider.stage}-CognitoUserPoolClientId
  
  CognitoUserPoolDomainName:
    Description: Cognito User Pool Domain Name
    Value: !Ref CognitoUserPoolDomain
    Export:
      Name: ${self:provider.stage}-CognitoUserPoolDomainName
  
  CognitoHostedUIURL:
    Description: Cognito Hosted UI URL
    Value: !Sub 
      - 'https://${Domain}.auth.${Region}.amazoncognito.com'
      - Domain: !Ref CognitoUserPoolDomain
        Region: ${self:provider.region}
    Export:
      Name: ${self:provider.stage}-CognitoHostedUIURL
  
  UsersTableName:
    Description: Users DynamoDB Table Name
    Value: !Ref UsersTable
    Export:
      Name: ${self:provider.stage}-UsersTableName
  
  JobDetailsTableName:
    Description: Job Details DynamoDB Table Name
    Value: !Ref JobDetailsTable
    Export:
      Name: ${self:provider.stage}-JobDetailsTableName
  
  PDFsBucketName:
    Description: S3 Bucket Name for PDF Storage
    Value: !Ref PDFsBucket
    Export:
      Name: ${self:provider.stage}-PDFsBucketName
  
  LongJobQueueUrl:
    Description: SQS Queue URL for Long Job Processing
    Value: !Ref LongJobQueue
    Export:
      Name: ${self:provider.stage}-LongJobQueueUrl
  
  LongJobQueueArn:
    Description: SQS Queue ARN for Long Job Processing
    Value: !GetAtt LongJobQueue.Arn
    Export:
      Name: ${self:provider.stage}-LongJobQueueArn
  
  BillsTableName:
    Description: Bills DynamoDB Table Name
    Value: !Ref BillsTable
    Export:
      Name: ${self:provider.stage}-BillsTableName
  
  WebhooksTableName:
    Description: Webhooks DynamoDB Table Name
    Value: !Ref WebhooksTable
    Export:
      Name: ${self:provider.stage}-WebhooksTableName
  
  WebhookHistoryTableName:
    Description: Webhook History DynamoDB Table Name
    Value: !Ref WebhookHistoryTable
    Export:
      Name: ${self:provider.stage}-WebhookHistoryTableName

